### ISSUE TITLE
Unable to determine the domain name

### ISSUE THREAD

**Issue by buratinodev** [Wizcorp/mocha-reporter#3] opened 2017-12-07 09:02 UTC
>>> logs: Error: Unable to determine the domain name
     >>> logs:     at new ClientRequest (_http_client.js:83:13)
     >>> logs:     at Object.request (http.js:39:10)
     >>> logs:     at Context.<anonymous> (test/apitest-jlsticket.spec.js:48:14)

works when removing this reporter
![screen shot 2017-12-07 at 10 00 58](https://user-images.githubusercontent.com/3932029/33706832-a8982c16-db35-11e7-9dd4-cd952f55cded.png)

**Comment by stelcheck** [comment] 2017-12-07 11:29
What you mean is that when you use this reporter, the test fails, but when you do not, the test passes?

**Comment by buratinodev** [comment] 2017-12-07 11:46
yes, that's it. But now I'm wondering if it's really a reporter failure, or if the failure comes from one of  the dependencies, since it seems to be something about DNS-resolution

**Comment by stelcheck** [comment] 2017-12-07 11:55
It seems unlikely it would be reportee related. Would it be possible for you to put online a demo that reproduces this issue so that we may have a look? I would be happy to try to investigate this isssue.

**Comment by buratinodev** [comment] 2017-12-08 08:38
Unfortunately my schedule is really tight for the coming days, and god knows after that. But it's basically a mocha test, with a describe, before (start server) and a couple of it( request(url) ) against a local loopback server on port 3000. I read something about ember, see this issue: https://github.com/xomaczar/ember-cli-styles-reloader/issues/18

**Comment by buratinodev** [comment] 2017-12-08 12:46
I switched from calling localhost to a FQDN and now it works

**Comment by stelcheck** [comment] 2017-12-08 14:46
Seems safe to assume the issue is with ember at this point. Do you wish to keep this issue open, os should we close it?

**Comment by stelcheck** [comment] 2017-12-12 11:29
Will close for now, please feel free to re-open if you can contribute more details so to figure out this issue.

**Closed as completed by stelcheck** 2017-12-12 11:29 UTC
